spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Password.1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
logging:
  level: info
  level.root: info
  level.org.hibernate: debug
---
spring:
  profiles: staging
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: Password.1
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
logging:
  level: error
  level.root: info
  level.org.hibernate: info