spring:
  datasource:
    primary:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Password.1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
logging:
  level: info
  level.root: info
  level.org.hibernate: error
SCR_GENESIS_SEED: 3FT3JH1c1LxVAZZqG61VRcEaKnMjPzyHobU
SCR_MAILGUN_API_KEY: key-3c14d95e94ff3515c69e2a9199d1a127
SCR_MAILGUN_DOMAIN: demo.scienceroots.com


---
spring:
  profiles: staging
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: Password.1
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
logging:
  level: error
  level.root: info
  level.org.hibernate: info
SCR_GENESIS_SEED: 3FT3JH1c1LxVAZZqG61VRcEaKnMjPzyHobU
SCR_MAILGUN_API_KEY: key-3c14d95e94ff3515c69e2a9199d1a127
SCR_MAILGUN_DOMAIN: demo.scienceroots.com
SCR_MAILGUN_LOGIN: postmaster@demo.scienceroots.com
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: Password.1
    driver-class-name: org.postgresql.Driver
server:
  context-path: /api
logging:
  level: error
  level.root: info
  level.org.hibernate: info
SCR_GENESIS_SEED: 3FT3JH1c1LxVAZZqG61VRcEaKnMjPzyHobU
SCR_MAILGUN_API_KEY: key-3c14d95e94ff3515c69e2a9199d1a127
SCR_MAILGUN_DOMAIN: app.scienceroots.com
SCR_MAILGUN_LOGIN: postmaster@app.scienceroots.com