/**
 * Author:  svenseemann
 * Created: 24.02.2018
 */

INSERT INTO industries(name) VALUES ('Agriculture and Mining');
INSERT INTO industries(name) VALUES ('Farming and Ranching');
INSERT INTO industries(name) VALUES ('Fishing, Hunting and Forestry and Logging');
INSERT INTO industries(name) VALUES ('Mining and Quarrying');
INSERT INTO industries(name) VALUES ('Agriculture & Mining Other');
INSERT INTO industries(name) VALUES ('Business Services');
INSERT INTO industries(name) VALUES ('Accounting and Tax Preparation');
INSERT INTO industries(name) VALUES ('Advertising, Marketing and PR');
INSERT INTO industries(name) VALUES ('Data and Records Management');
INSERT INTO industries(name) VALUES ('Facilities Management and Maintenance');
INSERT INTO industries(name) VALUES ('HR and Recruiting Services');
INSERT INTO industries(name) VALUES ('Legal Services');
INSERT INTO industries(name) VALUES ('Management Consulting');
INSERT INTO industries(name) VALUES ('Payroll Services');
INSERT INTO industries(name) VALUES ('Sales Services');
INSERT INTO industries(name) VALUES ('Security Services');
INSERT INTO industries(name) VALUES ('Business Services Other');
INSERT INTO industries(name) VALUES ('Computer and Electronics');
INSERT INTO industries(name) VALUES ('Audio, Video and Photography');
INSERT INTO industries(name) VALUES ('Computers, Parts and Repair');
INSERT INTO industries(name) VALUES ('Consumer Electronics, Parts and Repair');
INSERT INTO industries(name) VALUES ('IT and Network Services and Support');
INSERT INTO industries(name) VALUES ('Instruments and Controls');
INSERT INTO industries(name) VALUES ('Network Security Products');
INSERT INTO industries(name) VALUES ('Networking equipment and Systems');
INSERT INTO industries(name) VALUES ('Office Machinery and Equipment');
INSERT INTO industries(name) VALUES ('Peripherals Manufacturing');
INSERT INTO industries(name) VALUES ('Semiconductor and Microchip Manufacturing');
INSERT INTO industries(name) VALUES ('Computer and Electronics Other');
INSERT INTO industries(name) VALUES ('Consumer Services');
INSERT INTO industries(name) VALUES ('Automotive Repair and Maintenance');
INSERT INTO industries(name) VALUES ('Funeral Homes and Services');
INSERT INTO industries(name) VALUES ('Laundry and Dry Cleaning');
INSERT INTO industries(name) VALUES ('Parking Lots and Garage Management');
INSERT INTO industries(name) VALUES ('Personal Care');
INSERT INTO industries(name) VALUES ('Photofinishing Services');
INSERT INTO industries(name) VALUES ('Consumer Services Other');
INSERT INTO industries(name) VALUES ('Education');
INSERT INTO industries(name) VALUES ('Colleges and Universities');
INSERT INTO industries(name) VALUES ('Elementary and Secondary Schools');
INSERT INTO industries(name) VALUES ('Libraries, Archives and Museums');
INSERT INTO industries(name) VALUES ('Sports, Arts, and Recreation Instruction');
INSERT INTO industries(name) VALUES ('Technical and Trade Schools');
INSERT INTO industries(name) VALUES ('Test Preparation');
INSERT INTO industries(name) VALUES ('Education Other');
INSERT INTO industries(name) VALUES ('Energy and Utilities');
INSERT INTO industries(name) VALUES ('Alternative Energy Sources');
INSERT INTO industries(name) VALUES ('Gas and Electric Utilities');
INSERT INTO industries(name) VALUES ('Gasoline and Oil Refineries');
INSERT INTO industries(name) VALUES ('Sewage Treatment Facilities');
INSERT INTO industries(name) VALUES ('Waste Management and Recycling');
INSERT INTO industries(name) VALUES ('Water Treatment and Utilities');
INSERT INTO industries(name) VALUES ('Energy and Utilities Other');
INSERT INTO industries(name) VALUES ('Financial Services');
INSERT INTO industries(name) VALUES ('Banks');
INSERT INTO industries(name) VALUES ('Credit Cards and Related Services');
INSERT INTO industries(name) VALUES ('Credit Unions');
INSERT INTO industries(name) VALUES ('Insurance and Risk Management');
INSERT INTO industries(name) VALUES ('Investment Banking and Venture Capital');
INSERT INTO industries(name) VALUES ('Lending and Mortgage');
INSERT INTO industries(name) VALUES ('Personal Financial Planning and Private Banking');
INSERT INTO industries(name) VALUES ('Securities Agents and Brokers');
INSERT INTO industries(name) VALUES ('Trust, Fiduciary, and Custody Activities');
INSERT INTO industries(name) VALUES ('Financial Services Other');
INSERT INTO industries(name) VALUES ('Government');
INSERT INTO industries(name) VALUES ('International Bodies and Organizations');
INSERT INTO industries(name) VALUES ('Local Government');
INSERT INTO industries(name) VALUES ('National Government');
INSERT INTO industries(name) VALUES ('State/Provincial Government');
INSERT INTO industries(name) VALUES ('Government Other');
INSERT INTO industries(name) VALUES ('Health, Pharmaceuticals, and Biotech');
INSERT INTO industries(name) VALUES ('Biotechnology');
INSERT INTO industries(name) VALUES ('Diagnostic Laboratories');
INSERT INTO industries(name) VALUES ('Doctors and Health Care Practitioners');
INSERT INTO industries(name) VALUES ('Hospitals');
INSERT INTO industries(name) VALUES ('Medical Devices');
INSERT INTO industries(name) VALUES ('Medical Supplies and Equipment');
INSERT INTO industries(name) VALUES ('Outpatient Care Centers');
INSERT INTO industries(name) VALUES ('Personal Health Care Products');
INSERT INTO industries(name) VALUES ('Pharmaceuticals');
INSERT INTO industries(name) VALUES ('Residential and Long-term Care Facilities');
INSERT INTO industries(name) VALUES ('Veterinary Clinics and Services');
INSERT INTO industries(name) VALUES ('Health, Pharmaceuticals, and Biotech Other');
INSERT INTO industries(name) VALUES ('Manufacturing');
INSERT INTO industries(name) VALUES ('Aerospace and Defense');
INSERT INTO industries(name) VALUES ('Alcoholic Beverages');
INSERT INTO industries(name) VALUES ('Automobiles, Boats and Motor Vehicles');
INSERT INTO industries(name) VALUES ('Chemicals and Petrochemicals');
INSERT INTO industries(name) VALUES ('Concrete, Glass and Building Materials');
INSERT INTO industries(name) VALUES ('Farming and Mining Machinery and Equipment');
INSERT INTO industries(name) VALUES ('Food and Dairy Product Manufacturing and Packaging');
INSERT INTO industries(name) VALUES ('Furniture Manufacturing');
INSERT INTO industries(name) VALUES ('Metals Manufacturing');
INSERT INTO industries(name) VALUES ('Nonalcoholic Beverages');
INSERT INTO industries(name) VALUES ('Paper and Paper Products');
INSERT INTO industries(name) VALUES ('Plastics and Rubber Manufacturing');
INSERT INTO industries(name) VALUES ('Textiles, Apparel and Accessories');
INSERT INTO industries(name) VALUES ('Tools, Hardware and Light Machinery');
INSERT INTO industries(name) VALUES ('Manufacturing Other');
INSERT INTO industries(name) VALUES ('Media and Entertainment');
INSERT INTO industries(name) VALUES ('Adult Entertainment');
INSERT INTO industries(name) VALUES ('Motion Picture Exhibitors');
INSERT INTO industries(name) VALUES ('Motion Picture and Recording Producers');
INSERT INTO industries(name) VALUES ('Newspapers, Books, and Periodicals');
INSERT INTO industries(name) VALUES ('Performing Arts');
INSERT INTO industries(name) VALUES ('Radio, Television Broadcasting');
INSERT INTO industries(name) VALUES ('Media and Entertainment Other');
INSERT INTO industries(name) VALUES ('Non-profit');
INSERT INTO industries(name) VALUES ('Advocacy Organizations');
INSERT INTO industries(name) VALUES ('Charitable Organizations and Foundations');
INSERT INTO industries(name) VALUES ('Professional Associations');
INSERT INTO industries(name) VALUES ('Religious Organizations');
INSERT INTO industries(name) VALUES ('Social and Membership Organizations');
INSERT INTO industries(name) VALUES ('Trade Groups and Labor Unions');
INSERT INTO industries(name) VALUES ('Non-profit Other');
INSERT INTO industries(name) VALUES ('Other');
INSERT INTO industries(name) VALUES ('Other');
INSERT INTO industries(name) VALUES ('Real Estate and Construction');
INSERT INTO industries(name) VALUES ('Architecture, Engineering and Design');
INSERT INTO industries(name) VALUES ('Construction Equipment and Supplies');
INSERT INTO industries(name) VALUES ('Construction and Remodeling');
INSERT INTO industries(name) VALUES ('Property Leasing and Management');
INSERT INTO industries(name) VALUES ('Real Estate Agents and Appraisers');
INSERT INTO industries(name) VALUES ('Real Estate Investment and Development');
INSERT INTO industries(name) VALUES ('Real Estate and Construction Other');
INSERT INTO industries(name) VALUES ('Retail');
INSERT INTO industries(name) VALUES ('Automobile Dealers');
INSERT INTO industries(name) VALUES ('Automobile Parts and Supplies');
INSERT INTO industries(name) VALUES ('Beer, Wine and Liquor Stores');
INSERT INTO industries(name) VALUES ('Clothing and Shoe Stores');
INSERT INTO industries(name) VALUES ('Department Stores');
INSERT INTO industries(name) VALUES ('Florist');
INSERT INTO industries(name) VALUES ('Furniture Stores');
INSERT INTO industries(name) VALUES ('Gasoline Stations');
INSERT INTO industries(name) VALUES ('Grocery and Specialty Stores');
INSERT INTO industries(name) VALUES ('Hardware and Building Material Dealers');
INSERT INTO industries(name) VALUES ('Jewelry, Luggage, and Leather Goods');
INSERT INTO industries(name) VALUES ('Office Supplies Stores');
INSERT INTO industries(name) VALUES ('Restaurants and Bars');
INSERT INTO industries(name) VALUES ('Sporting Goods, Hobby, Books and Music Stores');
INSERT INTO industries(name) VALUES ('Retail Others');
INSERT INTO industries(name) VALUES ('Software and Internet');
INSERT INTO industries(name) VALUES ('Data Analytics, Management, and Internet');
INSERT INTO industries(name) VALUES ('E-Commerce and Internet Business');
INSERT INTO industries(name) VALUES ('Games and Gaming');
INSERT INTO industries(name) VALUES ('Software');
INSERT INTO industries(name) VALUES ('Software and Internet Other');
INSERT INTO industries(name) VALUES ('Telecommunications');
INSERT INTO industries(name) VALUES ('Cable and Television Providers');
INSERT INTO industries(name) VALUES ('Telecommunications Equipment and Accessories');
INSERT INTO industries(name) VALUES ('Telephone Service Providers and Carriers');
INSERT INTO industries(name) VALUES ('Video and Teleconferencing');
INSERT INTO industries(name) VALUES ('Wireless and Mobile');
INSERT INTO industries(name) VALUES ('Telecommunications Other');
INSERT INTO industries(name) VALUES ('Transportation and Storage');
INSERT INTO industries(name) VALUES ('Air Couriers and Caro Services');
INSERT INTO industries(name) VALUES ('Airport, Harbor, and Terminal Operations');
INSERT INTO industries(name) VALUES ('Freight Hauling (Rail and Truck)');
INSERT INTO industries(name) VALUES ('Marine and Inland Shipping');
INSERT INTO industries(name) VALUES ('Moving Companies and Services');
INSERT INTO industries(name) VALUES ('Postal, Express Delivery and Couriers');
INSERT INTO industries(name) VALUES ('Warehousing and Storage');
INSERT INTO industries(name) VALUES ('Transportation and Storage Other');
INSERT INTO industries(name) VALUES ('Travel Recreation and Leisure');
INSERT INTO industries(name) VALUES ('Amusement Parks and Attractions');
INSERT INTO industries(name) VALUES ('Cruise Ship Operations');
INSERT INTO industries(name) VALUES ('Gambling and Gaming Lodging');
INSERT INTO industries(name) VALUES ('Participatory Sports and Recreation');
INSERT INTO industries(name) VALUES ('Passenger Airlines');
INSERT INTO industries(name) VALUES ('Rental Cars');
INSERT INTO industries(name) VALUES ('Resorts and Casinos');
INSERT INTO industries(name) VALUES ('Spectator Sports and Teams');
INSERT INTO industries(name) VALUES ('Taxi, Buses and Transit Systems');
INSERT INTO industries(name) VALUES ('Travel Agents and Services');
INSERT INTO industries(name) VALUES ('Travel, Recreations and Leisure Other');
INSERT INTO industries(name) VALUES ('Wholesale and Distribution');
INSERT INTO industries(name) VALUES ('Apparel Wholesalers');
INSERT INTO industries(name) VALUES ('Automobile Parts Wholesalers');
INSERT INTO industries(name) VALUES ('Beer, Wine and Liquor Wholesalers');
INSERT INTO industries(name) VALUES ('Chemicals and Plastics Wholesalers');
INSERT INTO industries(name) VALUES ('Grocery and Food Wholesalers');
INSERT INTO industries(name) VALUES ('Lumber and Construction Materials Wholesalers');
INSERT INTO industries(name) VALUES ('Metal and Mineral Wholesalers');
INSERT INTO industries(name) VALUES ('Office Equipment and Suppliers Wholesalers');
INSERT INTO industries(name) VALUES ('Petroleum Products Wholesalers');
INSERT INTO industries(name) VALUES ('Wholesale and Distribution Other');