INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Agriculture and Mining');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Farming and Ranching');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Fishing, Hunting and Forestry and Logging');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Mining and Quarrying');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Agriculture & Mining Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Business Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Accounting and Tax Preparation');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Advertising, Marketing and PR');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Data and Records Management');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Facilities Management and Maintenance');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'HR and Recruiting Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Legal Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Management Consulting');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Payroll Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Sales Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Security Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Business Services Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Computer and Electronics');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Audio, Video and Photography');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Computers, Parts and Repair');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Consumer Electronics, Parts and Repair');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'IT and Network Services and Support');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Instruments and Controls');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Network Security Products');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Networking equipment and Systems');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Office Machinery and Equipment');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Peripherals Manufacturing');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Semiconductor and Microchip Manufacturing');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Computer and Electronics Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Consumer Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Automotive Repair and Maintenance');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Funeral Homes and Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Laundry and Dry Cleaning');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Parking Lots and Garage Management');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Personal Care');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Photofinishing Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Consumer Services Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Education');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Colleges and Universities');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Elementary and Secondary Schools');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Libraries, Archives and Museums');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Sports, Arts, and Recreation Instruction');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Technical and Trade Schools');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Test Preparation');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Education Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Energy and Utilities');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Alternative Energy Sources');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Gas and Electric Utilities');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Gasoline and Oil Refineries');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Sewage Treatment Facilities');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Waste Management and Recycling');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Water Treatment and Utilities');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Energy and Utilities Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Financial Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Banks');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Credit Cards and Related Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Credit Unions');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Insurance and Risk Management');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Investment Banking and Venture Capital');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Lending and Mortgage');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Personal Financial Planning and Private Banking');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Securities Agents and Brokers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Trust, Fiduciary, and Custody Activities');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Financial Services Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Government');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'International Bodies and Organizations');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Local Government');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'National Government');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'State/Provincial Government');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Government Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Health, Pharmaceuticals, and Biotech');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Biotechnology');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Diagnostic Laboratories');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Doctors and Health Care Practitioners');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hospitals');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Medical Devices');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Medical Supplies and Equipment');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Outpatient Care Centers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Personal Health Care Products');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Pharmaceuticals');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Residential and Long-term Care Facilities');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Veterinary Clinics and Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Health, Pharmaceuticals, and Biotech Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Manufacturing');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Aerospace and Defense');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Alcoholic Beverages');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Automobiles, Boats and Motor Vehicles');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Chemicals and Petrochemicals');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Concrete, Glass and Building Materials');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Farming and Mining Machinery and Equipment');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Food and Dairy Product Manufacturing and Packaging');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Furniture Manufacturing');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Metals Manufacturing');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Nonalcoholic Beverages');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Paper and Paper Products');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Plastics and Rubber Manufacturing');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Textiles, Apparel and Accessories');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Tools, Hardware and Light Machinery');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Manufacturing Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Media and Entertainment');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Adult Entertainment');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Motion Picture Exhibitors');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Motion Picture and Recording Producers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Newspapers, Books, and Periodicals');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Performing Arts');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Radio, Television Broadcasting');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Media and Entertainment Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Non-profit');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Advocacy Organizations');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Charitable Organizations and Foundations');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Professional Associations');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Religious Organizations');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Social and Membership Organizations');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Trade Groups and Labor Unions');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Non-profit Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Real Estate and Construction');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Architecture, Engineering and Design');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Construction Equipment and Supplies');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Construction and Remodeling');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Property Leasing and Management');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Real Estate Agents and Appraisers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Real Estate Investment and Development');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Real Estate and Construction Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Retail');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Automobile Dealers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Automobile Parts and Supplies');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Beer, Wine and Liquor Stores');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Clothing and Shoe Stores');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Department Stores');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Florist');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Furniture Stores');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Gasoline Stations');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Grocery and Specialty Stores');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hardware and Building Material Dealers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Jewelry, Luggage, and Leather Goods');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Office Supplies Stores');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Restaurants and Bars');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Sporting Goods, Hobby, Books and Music Stores');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Retail Others');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Software and Internet');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Data Analytics, Management, and Internet');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'E-Commerce and Internet Business');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Games and Gaming');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Software');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Software and Internet Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Telecommunications');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Cable and Television Providers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Telecommunications Equipment and Accessories');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Telephone Service Providers and Carriers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Video and Teleconferencing');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Wireless and Mobile');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Telecommunications Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Transportation and Storage');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Air Couriers and Caro Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Airport, Harbor, and Terminal Operations');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Freight Hauling (Rail and Truck)');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Marine and Inland Shipping');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Moving Companies and Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Postal, Express Delivery and Couriers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Warehousing and Storage');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Transportation and Storage Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Travel Recreation and Leisure');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Amusement Parks and Attractions');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Cruise Ship Operations');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Gambling and Gaming Lodging');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Participatory Sports and Recreation');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Passenger Airlines');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Rental Cars');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Resorts and Casinos');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Spectator Sports and Teams');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Taxi, Buses and Transit Systems');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Travel Agents and Services');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Travel, Recreations and Leisure Other');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Wholesale and Distribution');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Apparel Wholesalers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Automobile Parts Wholesalers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Beer, Wine and Liquor Wholesalers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Chemicals and Plastics Wholesalers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Grocery and Food Wholesalers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Lumber and Construction Materials Wholesalers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Metal and Mineral Wholesalers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Office Equipment and Suppliers Wholesalers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Petroleum Products Wholesalers');
INSERT INTO industries(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Wholesale and Distribution Other');


INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Acoustics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Aeronautics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Agronomy');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Anatomy');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Anthropology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Archaeology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Astronomy');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Astrophysics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Bacteriology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Biochemistry');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Biology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Botany');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Cardiology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Cartography');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Chemistry');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Cosmology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Crystallography');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Ecology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Embryology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Endocrinology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Entomology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Enzymology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Forestry');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Gelotology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Genetics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Geochemistry');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Geodesy');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Geography');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Geology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Geophysics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hematology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Histology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Horology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hydrology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Ichthyology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Immunology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Linguistics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Mechanics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Medicine');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Meteorology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Metrology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Microbiology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Mineralogy');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Mycology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Neurology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Nucleonics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Nutrition');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Oceanography');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Oncology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Optics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Paleontology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Pathology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Petrology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Pharmacology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Physics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Physiology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Psychology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Radiology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Robotics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Seismology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Spectroscopy');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Systematics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Thermodynamics');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Toxicology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Virology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Volcanology');
INSERT INTO interests(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Zoology');

INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Afrikaans');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Albanian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Amharic');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Arabic (Egyptian Spoken)');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Arabic (Levantine)');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Arabic (Modern Standard)');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Arabic (Moroccan Spoken)');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Arabic (Overview)');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Aramaic');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Armenian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Assamese');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Aymara');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Azerbaijani');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Balochi');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Bamanankan');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Bashkort (Bashkir)');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Basque');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Belarusan');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Bengali');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Bhojpuri');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Bislama');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Bosnian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Brahui');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Bulgarian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Burmese');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Cantonese');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Catalan');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Cebuano');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Chechen');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Cherokee');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Croatian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Czech');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Dakota');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Danish');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Dari');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Dholuo');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Dutch');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'English');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Esperanto');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Estonian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Éwé');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Finnish');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'French');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Georgian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'German');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Gikuyu');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Greek');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Guarani');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Gujarati');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Haitian Creole');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hausa');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hawaiian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hawaiian Creole');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hebrew');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hiligaynon');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hindi');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Hungarian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Icelandic');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Igbo');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Ilocano');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Indonesian (Bahasa Indonesia)');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Inuit/Inupiaq');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Irish Gaelic');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Italian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Japanese');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Jarai');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Javanese');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'K’iche’');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Kabyle');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Kannada');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Kashmiri');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Kazakh');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Khmer');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'KhoekhoeKorean');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Kurdish');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Kyrgyz');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Lao');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Latin');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Latvian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Lingala');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Lithuanian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Macedonian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Maithili');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Malagasy');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Malay (Bahasa Melayu)');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Malayalam');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Mandarin (Chinese)');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Marathi');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Mende');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Mongolian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Nahuatl');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Navajo');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Nepali');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Norwegian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Ojibwa');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Oriya');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Oromo');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Pashto');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Persian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Polish');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Portuguese');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Punjabi');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Quechua');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Romani');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Romanian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Russian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Rwanda');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Samoan');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Sanskrit');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'SerbianShona');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Sindhi');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Sinhala');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Slovak');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Slovene');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Somali');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Spanish');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Swahili');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Swedish');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Tachelhit');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Tagalog');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Tajiki');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Tamil');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Tatar');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Telugu');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Thai');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Tibetic languages');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Tigrigna');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Tok Pisin');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Turkish');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Turkmen');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Ukrainian');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Urdu');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Uyghur');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Uzbek');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Vietnamese');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Warlpiri');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Welsh');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Wolof');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Xhosa');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Yakut');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Yiddish');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Yoruba');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Yucatec');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Zapotec');
INSERT INTO scr_languages(id, name) VALUES (uuid_in(md5(random()::text || now()::text)::cstring), 'Zulu');
